import { Unit } from './Unit';

export const Units: Unit[] = [
  { code: 'Sp', description: 'Servicios profesionales' },
  { code: 'm', description: 'Metro' },
  { code: 'kg', description: 'Kilogramo' },
  { code: 's', description: 'Segundo' },
  { code: 'A', description: 'Ampere' },
  { code: 'K', description: 'Kelvin' },
  { code: 'mol', description: 'Mol' },
  { code: 'cd', description: 'Candela' },
  { code: 'm²', description: 'Metro cuadrado' },
  { code: 'm³', description: 'Metro cúbico' },
  { code: 'm/s', description: 'Metro por segundo' },
  { code: 'm/s²', description: 'Metro por segundo cuadrado' },
  { code: '1/m', description: 'Uno por metro' },
  { code: 'kg/m³', description: 'Kilogramo por metro cubico' },
  { code: 'A/m²', description: 'Ampere por metro cuadrado' },
  { code: 'A/m', description: 'Ampere por metro' },
  { code: 'mol/m³', description: 'Mol por metro cubico' },
  { code: 'cd/m² ', description: 'Candela por metro cuadrado' },
  { code: '1', description: 'Uno (Indice de refracción)' },
  { code: 'rad', description: 'Radián' },
  { code: 'sr', description: 'Estereorradián' },
  { code: 'Hz', description: 'Hertz' },
  { code: 'N', description: 'Newton' },
  { code: 'Pa', description: 'Pascal' },
  { code: 'J', description: 'Joule' },
  { code: 'W', description: 'Watt' },
  { code: 'C', description: 'Coulomb' },
  { code: 'V', description: 'Volt' },
  { code: 'F', description: 'Farad' },
  { code: 'Ω', description: 'Ohm' },
  { code: 'S', description: 'Siemens' },
  { code: 'Wb', description: 'Weber' },
  { code: 'T', description: 'Tesla' },
  { code: 'H', description: 'Henry' },
  { code: '°C', description: 'Grado Celsius' },
  { code: 'lm', description: 'Lumen' },
  { code: 'lx', description: 'Lux' },
  { code: 'Bq', description: 'Becquerel' },
  { code: 'Gy', description: 'Gray' },
  { code: 'Sv', description: 'Sievert' },
  { code: 'kat', description: 'Katal' },
  { code: 'Pa·s', description: 'Pascal Segundo' },
  { code: 'N·m', description: 'Newton Metro' },
  { code: 'N/m', description: 'Newton por metro' },
  { code: 'rad/s', description: 'Radián por segundo' },
  { code: 'rad/s²', description: 'Radián por segundo al cuadrado' },
  { code: 'W/m²', description: 'Watt por metro cuadrado' },
  { code: 'J/K', description: 'Joule por Kelvin' },
  { code: 'J/(kg·K) ', description: 'Joule por Kilogramo Kelvin' },
  { code: 'J/kg', description: 'Joule por kilogramo' },
  { code: 'W/(m·K)', description: 'Watt por metro kevin' },
  { code: 'J/m³ ', description: 'Joule por metro cúbico' },
  { code: 'V/m', description: 'Volt por metro' },
  { code: 'C/m³', description: 'Coulomb por metro cúbico' },
  { code: 'C/m²', description: 'Coulomb por metro cuadrado' },
  { code: 'F/m', description: 'Farad por metro' },
  { code: 'H/m', description: 'Henry por metro' },
  { code: 'J/mol ', description: 'Joule por mol' },
  { code: 'J/(mol·K)', description: 'joule por mol kelvin' },
  { code: 'C/kg', description: 'Coulomb por kilogramo' },
  { code: 'Gy/s', description: 'Gray por segundo' },
  { code: 'W/sr', description: 'Watt por estereorradián' },
  { code: 'W/(m²·sr)', description: 'Watt por metro cuadrado estereorradián' },
  { code: 'kat/m³', description: 'Katal por metro cúbico' },
  { code: 'min', description: 'Minuto' },
  { code: 'h', description: 'Hora' },
  { code: 'd', description: 'Día' },
  { code: 'º', description: 'Grado' },
  { code: '´', description: 'Minuto' },
  { code: '´´', description: 'Segundo' },
  { code: 'L', description: 'Litro' },
  { code: 't', description: 'Tonelada' },
  { code: 'Np', description: 'Neper' },
  { code: 'B', description: 'Bel' },
  { code: 'eV', description: 'EletronVolt' },
  { code: 'u', description: 'Unidad de masa atómica unificada' },
  { code: 'ua', description: 'Unidad astronómica' },
  { code: 'Unid', description: 'Unidad' },
  { code: 'Gal', description: 'Galón' },
  { code: 'g', description: 'Gramo' },
  { code: 'Km', description: 'Kilometro' },
  { code: 'In', description: 'Pulgada' },
  { code: 'cm', description: 'Centimetro' },
  { code: 'mL', description: 'Mililitro' },
  { code: 'mm', description: 'Milimetro' },
  { code: 'Oz', description: 'Onzas' },
  { code: 'Otros', description: 'Otros' },
]
